# KallistiOS ##version##
#
# arch/dreamcast Makefile
# Copyright (C) 2001 Dan Potter
#

SUBDIRS=fs hardware kernel math sound util

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
