# KallistiOS ##version##
#
# examples/dreamcast/vmu/Makefile
# (c)2002 Megan Potter
#

all:
	$(KOS_MAKE) -C vmu_pkg
	$(KOS_MAKE) -C vmu_game
	$(KOS_MAKE) -C vmu_beep
	$(KOS_MAKE) -C vmu_lcd

clean:
	$(KOS_MAKE) -C vmu_pkg clean
	$(KOS_MAKE) -C vmu_game clean
	$(KOS_MAKE) -C vmu_beep clean
	$(KOS_MAKE) -C vmu_lcd clean

dist:
	$(KOS_MAKE) -C vmu_pkg dist
	$(KOS_MAKE) -C vmu_game dist
	$(KOS_MAKE) -C vmu_beep dist
	$(KOS_MAKE) -C vmu_lcd dist
