# KallistiOS ##version##
#
# examples/dreamcast/cpp/Makefile
# Copyright (C) 2001-2002 Megan Potter
#

all:
	$(KOS_MAKE) -C gltest
	$(KOS_MAKE) -C dcplib
	$(KOS_MAKE) -C clock
	$(KOS_MAKE) -C modplug_test
	$(KOS_MAKE) -C out_of_memory
	$(KOS_MAKE) -C concurrency

clean:
	$(KOS_MAKE) -C gltest clean
	$(KOS_MAKE) -C dcplib clean
	$(KOS_MAKE) -C clock clean
	$(KOS_MAKE) -C modplug_test clean
	$(KOS_MAKE) -C out_of_memory clean
	$(KOS_MAKE) -C concurrency clean

dist:
	$(KOS_MAKE) -C gltest dist
	$(KOS_MAKE) -C dcplib dist
	$(KOS_MAKE) -C clock dist
	$(KOS_MAKE) -C modplug_test dist
	$(KOS_MAKE) -C out_of_memory dist
	$(KOS_MAKE) -C concurrency dist


