# KallistiOS ##version##
#
# examples/dreamcast/pvr/yuv_converter/Makefile
# Copyright (C) 2023 Falco Girgis
#

all:
	$(KOS_MAKE) -C YUV420
	$(KOS_MAKE) -C YUV422

clean:
	$(KOS_MAKE) -C YUV420 clean
	$(KOS_MAKE) -C YUV422 clean

dist:
	$(KOS_MAKE) -C YUV420 dist
	$(KOS_MAKE) -C YUV422 dist
