# KallistiOS ##version##
#
# addons/libnavi/Makefile
# Copyright (C) 2002 Dan Potter
#

TARGET = libnavi.a

# IDE
OBJS += navi_ide.o

# Flash BIOS
OBJS += navi_flash.o

# SUBDIRS = fs
SUBDIRS =

include $(KOS_BASE)/addons/Makefile.prefab
