# KallistiOS ##version##
#
# examples/dreamcast/mruby/Makefile
#

all:
	$(KOS_MAKE) -C dreampresent
	$(KOS_MAKE) -C mrbtris

clean:
	$(KOS_MAKE) -C dreampresent clean
	$(KOS_MAKE) -C mrbtris clean

dist:
	$(KOS_MAKE) -C dreampresent dist
	$(KOS_MAKE) -C mrbtris dist

