# KallistiOS ##version##
#
# kernel/libc/Makefile
# Copyright (C)2004 Megan Potter
#

SUBDIRS = koslib newlib pthreads c11 posix

all: subdirs
clean: clean_subdirs

include $(KOS_BASE)/Makefile.prefab
