# KallistiOS ##version##
#
# examples/dreamcast/video/Makefile
# Copyright (C) 2002 Megan Potter
#

all:
	$(KOS_MAKE) -C bfont
	$(KOS_MAKE) -C palmenu
	$(KOS_MAKE) -C minifont

clean:
	$(KOS_MAKE) -C bfont clean
	$(KOS_MAKE) -C palmenu clean
	$(KOS_MAKE) -C minifont clean

dist:
	$(KOS_MAKE) -C bfont dist
	$(KOS_MAKE) -C palmenu dist
	$(KOS_MAKE) -C minifont dist
