# KallistiOS ##version##
#
# utils/naomibintool/Makefile
# Copyright (C) 2020 Lawrence Sebald
#

all: naomibintool

naomibin: naomibintool.c
	$(CC) -o naomibintool naomibintool.c

clean:
	-rm -f naomibintool
