#
# Libdream Examples
# (c)2000-2001 Megan Potter
#

TARGET = $(BIN).elf

all: $(TARGET)

include $(KOS_BASE)/Makefile.rules

clean:
	-rm -f $(TARGET) $(OBJS) $(EXTRA_CLEAN)

rm-elf:
	-rm -f $(TARGET)

$(TARGET): $(OBJS)
	kos-cc -o $(TARGET) $(OBJS)

run: $(TARGET)
	$(KOS_LOADER) $(TARGET)

dist: $(TARGET)
	-rm -f $(OBJS) $(EXTRA_CLEAN)
	$(KOS_STRIP) $(TARGET)

